from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.RunSQL(
            sql="""
CREATE TABLE djoutbox_pending (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    routing_key   TEXT NOT NULL,
    body          BYTEA NOT NULL,
    tracking_ids  JSONB NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    send_after    TIMESTAMP WITH TIME ZONE NOT NULL,
    expiration    INTERVAL
);
CREATE INDEX djoutbox_pending_poll_idx
    ON djoutbox_pending (send_after, created_at);

CREATE TABLE djoutbox_sent (
    id            BIGINT NOT NULL,
    routing_key   TEXT NOT NULL,
    body          BYTEA NOT NULL,
    tracking_ids  JSONB NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    send_after    TIMESTAMP WITH TIME ZONE NOT NULL,
    expiration    INTERVAL,
    sent_at       TIMESTAMP WITH TIME ZONE NOT NULL
) PARTITION BY RANGE (created_at);
CREATE INDEX djoutbox_sent_created_at_idx ON djoutbox_sent (created_at);
CREATE INDEX djoutbox_sent_routing_key_idx ON djoutbox_sent (routing_key);

CREATE OR REPLACE FUNCTION djoutbox_notify_insert() RETURNS TRIGGER AS $$
BEGIN
    IF NEW.send_after <= NOW() THEN
        PERFORM pg_notify('djoutbox_channel', '');
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER djoutbox_notify_trigger
    AFTER INSERT ON djoutbox_pending
    FOR EACH ROW
    EXECUTE FUNCTION djoutbox_notify_insert();
            """,
            reverse_sql="""
DROP TRIGGER IF EXISTS djoutbox_notify_trigger ON djoutbox_pending;
DROP FUNCTION IF EXISTS djoutbox_notify_insert();
DROP TABLE IF EXISTS djoutbox_sent CASCADE;
DROP TABLE IF EXISTS djoutbox_pending CASCADE;
            """,
        ),
    ]
